name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check PR title
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/pr-title

      - name: Build & test
        uses: ./.github/actions/build